<script lang="ts">
    import Button from "$lib/components/general/Button.svelte";
    import DropdownSelectMultiple from "$lib/components/general/DropdownSelectMultiple.svelte";
    import DropdownSelectSingle from "$lib/components/general/DropdownSelectSingle.svelte";
    import SubmitButton from "$lib/components/general/SubmitButton.svelte";
    import Toggle from "$lib/components/general/Toggle.svelte";
    import { PROB_DIFFICULTIES, PROB_FOCUSES, type ProbDifficulty, type ProbFocus } from "$lib/constants";
    import { currentUser } from "$lib/stores/auth";
    import { editableContests } from "$lib/stores/contests";
    import { correctors } from "$lib/stores/correctors";
    import type { EditableProb } from "$lib/types";
    import { getContestEditedState, getProbEditedState } from "$lib/utils";
    import { createEventDispatcher } from "svelte";

    let { editableProb, changesSaved }: { editableProb: EditableProb, changesSaved: boolean } = $props();

    $effect(() => {
        console.log("correctors: ", $correctors[getProbEditedState(editableProb).author]);
    });

    const dispatch = createEventDispatcher<{
        "change-diff": { value: ProbDifficulty },
        "change-focus": { value: ProbFocus },
        "change-auto": { value: boolean },
        "change-infinite": { value: boolean },
        "change-online": { value: boolean },
        "change-contests": { value: string[] },
        "change-author": { value: string },
        "save-changes": {}
    }>();


    let authorHovered: boolean = $state(false);


</script>




<main>
    <div class="title">
        <div class="left">
            <i class="fa-solid fa-gear"></i>
            <h2>settings</h2>
        </div>
        <div class="right">
            <button class="save-changes" class:saved={ changesSaved } onclick={ () => { dispatch("save-changes", {}); } }>Save changes</button>
        </div>
    </div>
    <div class="content">
        <div class="diff row">
            <p class="text">
                Difficulty:
            </p>
            <DropdownSelectSingle
                selected={{ id: getProbEditedState(editableProb).diff, value: getProbEditedState(editableProb).diff }}
                possible={ PROB_DIFFICULTIES.map(d => ({ id: d, value: d })) }
                onchangeFunction={(id) => {dispatch("change-diff", { value: id as ProbDifficulty})}}
            />
        </div>
        <div class="focus row">
            <p class="text">
                Focus:
            </p>
            <DropdownSelectSingle
                selected={{ id: getProbEditedState(editableProb).focus, value: getProbEditedState(editableProb).focus }}
                possible={ PROB_FOCUSES.map(f => ({ id: f, value: f })) }
                onchangeFunction={(id) => {dispatch("change-focus", { value: id as ProbFocus})}}
            />
        </div>
        <div class="auto row">
            <p class="text">Autogenerated:</p>
            <Toggle value={ getProbEditedState(editableProb).auto } onChangeFunction={(value) => { dispatch("change-auto", { value: value }); }} />
        </div>
        <div class="infinite row">
            <p class="text">Infinite:</p>
            <Toggle value={ getProbEditedState(editableProb).infinite } onChangeFunction={(value) => { dispatch("change-infinite", { value: value }); }} />
        </div>
        <div class="online row">
            <p class="text">Online:</p>
            <Toggle value={ getProbEditedState(editableProb).online } onChangeFunction={(value) => { dispatch("change-online", { value: value }); }} />
        </div>
        <div class="contests row">
            <p class="text">Constests:</p>
            <DropdownSelectMultiple
            selected={ getProbEditedState(editableProb).contests.map(contest => ({ id: contest, value: getContestEditedState($editableContests[contest]).name })) }
            possible={ Object.entries($editableContests).map(item => ({ id: item[0], value: getContestEditedState(item[1]).name })) }
            onchangeFunction={ (value) => { dispatch("change-contests", { value: value }); }}
            />
        </div>
        <div class="author row">
            <div class="left-wrapper">
                <div class="text-wrapper" onmouseenter={() => { if (getProbEditedState(editableProb).author != "") { authorHovered = true; }}} onmouseleave={() => { authorHovered = false; }}>
                    <p class="text">
                        Author: 
                        <span class="bold" class:you={ getProbEditedState(editableProb).author == $currentUser?.id } class:nobody={ getProbEditedState(editableProb).author == "" } >{ getProbEditedState(editableProb).author == $currentUser?.id ? "you" : getProbEditedState(editableProb).author == "" ? "nobody" : $correctors[getProbEditedState(editableProb).author].username }</span>
                    </p>
                </div>
                <p class="email" class:visible={ authorHovered } >{ getProbEditedState(editableProb).author != "" ? $correctors[getProbEditedState(editableProb).author].email == undefined ? "email visibility is off" : $correctors[getProbEditedState(editableProb).author].email : "" }</p>
            </div>
            <div class="right-wrapper">
                {#if getProbEditedState(editableProb).author == "" || getProbEditedState(editableProb).author == $currentUser?.id }
                <Button class="" theme={ getProbEditedState(editableProb).author == "" ? "yellow" : "pink" } onclick={() => {
                    if (getProbEditedState(editableProb).author == "") {
                        if ($currentUser) {
                            dispatch("change-author", { value: $currentUser.id });
                        }
                    } else {
                        dispatch("change-author", { value: "" });
                    }
                }}>
                    {#if getProbEditedState(editableProb).author == $currentUser?.id }
                    <i class="fa-solid fa-paper-plane"></i>
                    <p>give away</p>
                    {:else}
                    <i class="fa-regular fa-square-plus"></i>
                    <p>get</p>
                    {/if}
                </Button>
                {/if}
            </div>
        </div>
    </div>
</main>


<style lang="scss">

    main {
        padding: 20px;
        display: flex;
        align-items: center;
        flex-direction: column;
        gap: 20px;
        min-width: 350px;
        box-shadow: 0px 0px 10px 0px #00000010;
        border-radius: 10px;
        // background-color: color-mix(in srgb, var(--color-orange) 2%, transparent 98%);
        // border: 1px color-mix(in srgb, var(--color-orange) 40%, transparent 60%) solid;
        
        .title {
            display: flex;
            justify-content: space-between;
            width: 100%;

            .left {
                display: flex;
                align-items: center;
                justify-content: center;
                gap: 10px;
                h2 {
                    font-size: 20px;
                    font-family: 'Fredoka';
                    font-weight: 600;
                    color: #333333;
                    margin: 0px;
                }
    
                i {
                    font-size: 25px;
                    color: #444444;
                    transform: translateY(3px);
                }

            }

            .right {
                display: flex;
                align-items: center;
                justify-content: center;

                button.save-changes {
                    all: unset;
                    cursor: pointer;
                    padding: 7px 15px;
                    font-family: 'Fredoka';
                    font-size: 16px;
                    font-weight: 500;
                    background-color: #F0F0F0;
                    border-radius: 4px;
                    color: black;
                    transition: all cubic-bezier(0.215, 0.610, 0.355, 1) 0.4s;

                    &:hover {
                        background-color: black;
                        color: white;
                        transition: all cubic-bezier(0.215, 0.610, 0.355, 1) 0.15s;
                        // transition: all 0s;
                    }

                    &.saved {
                        color: #888888;
                        background-color: #F0F0F0;
                    }
                }

            }
            
        }

        .content {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: center;
            gap: 15px;
            width: 100%;


            .row {
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                align-items: center;
                gap: 15px;
                width: 100%;

                p {
                    font-family: 'Fredoka';
                    font-size: 16px;
                    color: 333333;
                    margin: 0px;
                }

                &.diff {
                    align-items: start;

                    p {
                        margin-top: 8px;
                    }
                }
                &.focus {
                    align-items: start;

                    p {
                        margin-top: 8px;
                    }
                }
                &.contests {
                    align-items: start;

                    p {
                        margin-top: 8px;
                    }
                }

                &.author {
                    
                    .left-wrapper {
                        position: relative;
                        
                        .text-wrapper {
                            cursor: pointer;

                            .bold {
                                font-family: 'Lexend';
                                font-weight: 700;
                            }

                            .you {
                                color: var(--color-orange);
                            }
                            .nobody {
                                color: #999999;
                            }
                        }

                        .email {
                            position: absolute;
                            top: 0px;
                            left: 50%;
                            transform: translateX(-50%);
                            text-wrap: nowrap;
    
                            font-size: 12px;
                            font-weight: 400;
                            font-family: 'Fredoka';
                            background-color: #FAFAFA;
                            border-radius: 3px;
                            margin: 0px;
                            padding: 5px 10px;
                            box-sizing: border-box;
                            box-shadow: 0px 0px 5px #00000033;
                            opacity: 0;
                            z-index: -1;
                            transition: all cubic-bezier(0.215, 0.610, 0.355, 1) 0.3s;
                        
                            &.visible {
                                opacity: 1;
                                top: 30px;
                            }
                        }

                    }

                    .right-wrapper {
                        p {
                            font-family: 'Fredoka';
                            font-size: 16px;
                            font-weight: 500;
                            transform: translateY(-1px);
                        }
                        i {
                            font-size: 15px;
                        }
                    }
                }
            }
        }
    }


</style>
